# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


entry_one = Entry.create(cuid: "a", date: Time.now.httpdate, entry_text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A diam maecenas sed enim ut sem viverra aliquet. Molestie nunc non blandit massa enim nec dui nunc mattis. Leo in vitae turpis massa sed elementum. Sollicitudin ac orci phasellus egestas. Viverra mauris in aliquam sem fringilla ut. Feugiat scelerisque varius morbi enim. Turpis in eu mi bibendum neque. Libero justo laoreet sit amet cursus. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Curabitur vitae nunc sed velit dignissim sodales. Ipsum consequat nisl vel pretium lectus quam id. In vitae turpis massa sed. Rhoncus aenean vel elit scelerisque mauris.
    Egestas dui id ornare arcu odio ut sem nulla pharetra. Neque laoreet suspendisse interdum consectetur libero id. Aliquet enim tortor at auctor urna nunc. Felis eget nunc lobortis mattis aliquam faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Enim praesent elementum facilisis leo vel fringilla est. Pellentesque sit amet porttitor eget dolor. Ac placerat vestibulum lectus mauris ultrices eros. Erat imperdiet sed euismod nisi porta lorem. Ac turpis egestas sed tempus urna et pharetra pharetra. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tortor posuere ac ut consequat semper. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Sed id semper risus in hendrerit gravida.
    Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Felis donec et odio pellentesque. Mauris a diam maecenas sed enim. Tortor aliquam nulla facilisi cras. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Facilisis volutpat est velit egestas dui id. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. At quis risus sed vulputate odio ut. Tortor id aliquet lectus proin. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Senectus et netus et malesuada fames ac turpis egestas. Lacus luctus accumsan tortor posuere ac. Venenatis a condimentum vitae sapien pellentesque habitant morbi. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Nisl suscipit adipiscing bibendum est.")

entry_two = Entry.create(cuid: "ab", date: Time.now.httpdate, entry_text: "Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Viverra accumsan in nisl nisi scelerisque eu ultrices. Eget mi proin sed libero enim sed faucibus. Sapien faucibus et molestie ac. Massa vitae tortor condimentum lacinia. Est ultricies integer quis auctor elit. Fermentum iaculis eu non diam. Lectus mauris ultrices eros in cursus turpis. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Commodo ullamcorper a lacus vestibulum. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Pellentesque pulvinar pellentesque habitant morbi tristique. Purus in mollis nunc sed. Orci ac auctor augue mauris. Eu consequat ac felis donec et odio pellentesque diam volutpat. In arcu cursus euismod quis. Diam quam nulla porttitor massa id neque. Risus nullam eget felis eget nunc lobortis.")
entry_three = Entry.create(cuid: "ac", date: Time.now.httpdate, entry_text: "Id aliquet lectus proin nibh nisl condimentum. Senectus et netus et malesuada fames ac turpis egestas. Morbi enim nunc faucibus a pellentesque sit amet. Sit amet risus nullam eget felis. Dui faucibus in ornare quam viverra orci sagittis. Sed sed risus pretium quam vulputate dignissim. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Urna cursus eget nunc scelerisque viverra. Ornare arcu odio ut sem nulla pharetra diam sit. Amet mattis vulputate enim nulla aliquet porttitor. Netus et malesuada fames ac turpis egestas sed tempus urna. Viverra mauris in aliquam sem fringilla ut morbi. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Massa ultricies mi quis hendrerit dolor magna eget est. Dignissim convallis aenean et tortor at risus viverra adipiscing. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Eu feugiat pretium nibh ipsum consequat. Gravida rutrum quisque non tellus orci ac auctor augue. Enim lobortis scelerisque fermentum dui faucibus in ornare quam.")